### ISSUE TITLE
compatibilité avec Smarty 5

### ISSUE THREAD

**Issue by destrieux** [allinappli/frenchCodePost-civicrm#6]
Bonjour l'utilisation de frenchCodePost-civicrm-1.1 avec Smarty 5 induit une erreur fatale de wordpress
les logs suivants sont produits : 
Merci +++ de votre aide 

--------
[23-Sep-2024 16:08:26 UTC] PHP Fatal error:  Uncaught Error: Cannot access protected property Smarty\Smarty::$template_dir in /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php:26
Stack trace:
#0 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/ext/frenchCodePost-civicrm-1.1/frenchcodepostaux.civix.php(99): Smarty->__get('template_dir')
#1 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/ext/frenchCodePost-civicrm-1.1/frenchcodepostaux.php(14): _frenchcodepostaux_civix_civicrm_config(Object(CRM_Core_Config))
#2 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(276): frenchcodepostaux_civicrm_config(Object(CRM_Core_Config), Array)
#3 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(136): CRM_Utils_Hook->runHooks(Array, 'civicrm_config', 2, Object(CRM_Core_Config), Array, NULL, NULL, NULL, NULL)
#4 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(314): CRM_Utils in /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php on line 26

**Comment by dev-allinappli** [comment]
elle n'a pas encore été testée avec Smarty5. Ça ne saurait tarder car nous sommes en train de préparer une v2 avec une nouvelle fonctionnalité super utile :-). Elle devrait pouvoir être publiée d'ici 2 semaines grand maximum.

**Comment by destrieux** [comment]
Ça c est du teasing😉Super pratique en tout cas merci ++++Envoyé de mon iPhoneLe 23 sept. 2024 à 18:40, ALL IN APPLI admin ***@***.***> a écrit :﻿
elle n'a pas encore été testée avec Smarty5. Ça ne saurait tarder car nous sommes en train de préparer une v2 avec une nouvelle fonctionnalité super utile :-). Elle devrait pouvoir être publiée d'ici 2 semaines grand maximum.

**Comment by wyde22** [comment]
@allinappliadmin le civix upgrade ne fonctionne pas. voici l'erreur remonté dans le terminal : 
```
PHP Warning:  Phar::mapPhar(): open_basedir restriction in effect. File(/usr/local/bin/civix) is not within the allowed path(s): (/var/www/vhosts/testwpcivi.appli.in/:/tmp/) in /usr/local/bin/civix on line 10
PHP Warning:  require(phar://box-auto-generated-alias-05d4950b3879.phar/.box/bin/check-requirements.php): Failed to open stream: phar error: invalid url or non-existent phar "phar://box-auto-generated-alias-05d4950b3879.phar/.box/bin/check-requirements.php" in /usr/local/bin/civix on line 12
PHP Fatal error:  Uncaught Error: Failed opening required 'phar://box-auto-generated-alias-05d4950b3879.phar/.box/bin/check-requirements.php' (include_path='.:/opt/plesk/php/8.3/share/pear') in /usr/local/bin/civix:12
Stack trace:
#0 {main}
  thrown in /usr/local/bin/civix on line 12
```

**Comment by dev-allinappli** [comment]
une histoire de permissions je pense. je viens de l'effectuer

**Comment by wyde22** [comment]
ok

**Comment by dev-allinappli** [comment]
testé et confirmé avec Smarty v4, la v5 ne semble pas compatible

**Comment by dev-allinappli** [comment]
@destrieux peux-tu tester la dernière version que l'on vient de mettre à jour avec le nouveau profil (je t'ai mis un message explicatif sur Mattermost) ?

**Comment by destrieux** [comment]
bonjou rje regarde au plus vire mais c’est un peu bousculé en ce moment : ) 
merci +++

Christophe Destrieux, 
Unité iBrain UMRS INSERM U1253, Université de Tours 
https://ibrain.univ-tours.fr/

Service de Neurochirurgie 
et Laboratoire d'Anatomie - Faculté de Médecine - 10 Bd Tonnellé - 37032 Tours - France 
tel (33) 2 47 36 61 36 - fax (33) 2 47 36 62 07

**Comment by dev-allinappli** [comment]
testé sur standalone 5.79alpha1 avec Smarty v5 sans difficulté. à tester sur d'autres CMS mais a priori ok

**Comment by destrieux** [comment]
Merci beaucoup ; ca marche parfaitement sur wordpress 6.7.1

**Comment by dev-allinappli** [comment]
super nouvelle ! merci pour ton retour.
